apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migration-job
          image: ghcr.io/inspired-consulting/threat_shield-app:latest
          command: ["mix", "ecto.migrate"]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
      restartPolicy: Never
      imagePullSecrets:
        - name: github-container-registry
