name: Deploy

on:
  push:
    branches:
      - 56-setup-dev-environment-devthreatshieldeu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          kubectl config use-context threatshield-context
        env:
          CONTEXT_NAME: threatshield-context

      - name: Deploy to Kubernetes
        run: |
          kubectl config view
