name: Run Tests

on:
  push:
    branches:
      - preparation-branch-for-tests-in-pipeline
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Elixir and Mix
        uses: erlef/setup-beam@v1
        with:
          otp-version: 22.2
          elixir-version: 1.12.3

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test

      - name: Set workflow status to failed if any step fails
        if: ${{ failure() }}
        run: exit 1
